### ISSUE TITLE
Schema: nix projects.significance

### ISSUE THREAD

**Issue by wolverdude** [peida2015/SciTwits-Proposal#6]
`projects.significance`. This should go in the `description`. Perhaps `description` should actually be called `abstract`...

**Comment by peida2015** [comment]
'project.significance' is meant to highlight a project's purpose to a general audience without using science jargon.  I'm changing the schema to reflect this and let you know when it's ready.

**Comment by wolverdude** [comment]
I would caution you from adding too many fields to the new project form. Remember this is not for real scientists but busy employers trying out your app. Make it as easy as possible to interact with it. That means having fewer fields to fill in.

**Comment by peida2015** [comment]
Good point, I will limit the number of required fields.
